[workspace]
resolver = "2"
members = [
    "crates/cek-contract",
    "crates/cek-host-kernel",
    "crates/cek-peer-kernel",
    "crates/cek-ops-baseline",
    "crates/cek-peer-wasm",
    "crates/cek-cli",
    "extensions/cek-ext-ui",
    "extensions/cek-ops-ui",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"
repository = "https://github.com/bitplorer/cek-runtime"
rust-version = "1.70"

[workspace.dependencies]
cek-contract = { path = "crates/cek-contract" }
cek-host-kernel = { path = "crates/cek-host-kernel" }
cek-peer-kernel = { path = "crates/cek-peer-kernel" }
cek-peer-wasm = { path = "crates/cek-peer-wasm" }
cek-ops-baseline = { path = "crates/cek-ops-baseline" }
cek-ops-ui = { path = "extensions/cek-ops-ui" }
cek-ext-ui = { path = "extensions/cek-ext-ui" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
ed25519-dalek = { version = "2.1.1", default-features = false, features = ["std"] }

